---
- import_playbook: setup-spacemacs.yml
- import_playbook: gopls.yml
- import_playbook: godoc.yml
- import_playbook: goimports.yml
- import_playbook: gorename.yml
- import_playbook: guru.yml
- import_playbook: gotests.yml
- import_playbook: fillstruct.yml
- import_playbook: gomodifytags.yml
- import_playbook: godoctor.yml
- import_playbook: gopkgs.yml
- import_playbook: impl.yml
- import_playbook: godef.yml
- import_playbook: golangci-lint.yml
- import_playbook: gofumpt.yml
- import_playbook: oserrorsgodernize.yml

- name: Ensure Spacemacs go layer is set up
  hosts: all
